# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.CharField(max_length=200),
        ),
    ]
