# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_auto_20170214_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.IntegerField(),
        ),
    ]
